agents:
  queue: macos-14

steps:
  - name: ':copyright: License Audit'
    agents:
      queue: opensource
    plugins:
      docker-compose#v3.7.0:
        run: license_finder
    command: /bin/bash -lc '/scan/scripts/license_finder.sh'

  - label: ":hammer: CLI Binaries"
    key: build
    commands:
      - make build-all
    plugins:
      artifacts#v1.5.0:
        upload:
          - bin/**/*

  - group: ":lint-roller: Linting"
    steps:
      - label: ":lint-roller::go: Lint Go Code"
        commands:
          - make go-lint
      - label: ":lint-roller::npm: Lint NPM Dependencies"
        commands:
          - make npm-lint

  # Run the unit tests
  - label: Unit Tests
    commands:
      - make unit-tests

  - label: ":terminal: CLI Integration Tests"
    depends_on: build
    env:
      NODE_VERSION: 18
    commands:
      - bundle install
      - chmod +x bin/arm64-macos-bugsnag-cli
      - bundle exec maze-runner features/cli
    plugins:
      artifacts#v1.5.0:
        download:
          - bin/arm64-macos-bugsnag-cli
        upload:
          - maze_output/**/*

  - label: ":android: Integration Tests"
    depends_on: build
    commands:
      - bundle install
      - chmod +x bin/arm64-macos-bugsnag-cli
      - bundle exec maze-runner features/android
    env:
      JAVA_VERSION: 17
    plugins:
      artifacts#v1.5.0:
        download:
          - bin/arm64-macos-bugsnag-cli
        upload:
          - maze_output/**/*

  - label: ":dartlang: Integration Tests"
    depends_on: build
    commands:
      - bundle install
      - chmod +x bin/arm64-macos-bugsnag-cli
      - bundle exec maze-runner features/dart
    env:
      FLUTTER_BIN: "/opt/flutter/3.19.0/bin/flutter"
    plugins:
      artifacts#v1.5.0:
        download:
          - bin/arm64-macos-bugsnag-cli
        upload:
          - maze_output/**/*

  - label: Xcode Integration Tests
    depends_on: build
    env:
      XCODE_VERSION: 15
    commands:
      - bundle install
      - chmod +x bin/arm64-macos-bugsnag-cli
      - bundle exec maze-runner features/xcode
    plugins:
      artifacts#v1.5.0:
        download:
          - bin/arm64-macos-bugsnag-cli
        upload:
          - maze_output/**/*

  - label: ":javascript: Integration Tests"
    depends_on: build
    commands:
      - chmod +x bin/arm64-macos-bugsnag-cli
      - bundle install
      - bundle exec maze-runner features/js
    plugins:
      artifacts#v1.5.0:
        download:
          - bin/arm64-macos-bugsnag-cli
        upload:
          - maze_output/**/*

  - label: ":video_game: Unity Android Integration Tests"
    depends_on: build
    env:
      UNITY_VERSION: 6000.0.25f1
    commands:
      - chmod +x bin/arm64-macos-bugsnag-cli
      - bundle install
      - bundle exec maze-runner features/unity-android
    plugins:
      artifacts#v1.5.0:
        download:
          - bin/arm64-macos-bugsnag-cli
        upload:
          - maze_output/**/*

  - group: ":react: React Native"
    steps:
      - label: "RN 0.69 :ios: Integration Tests"
        skip: "issue with Boost https://github.com/facebook/react-native/issues/42180"
        depends_on: build
        agents:
          queue: macos-12-arm
        env:
          XCODE_VERSION: 13
        commands:
          - chmod +x bin/arm64-macos-bugsnag-cli
          - bundle install
          - bundle exec maze-runner features/react-native-ios/rn0_69.feature
        plugins:
          artifacts#v1.5.0:
            download:
              - bin/arm64-macos-bugsnag-cli
            upload:
              - maze_output/**/*

      - label: "RN 0.70 :ios: Integration Tests"
        depends_on: build
        agents:
          queue: macos-12-arm
        env:
          XCODE_VERSION: 13
        commands:
          - chmod +x bin/arm64-macos-bugsnag-cli
          - bundle install
          - bundle exec maze-runner features/react-native-ios/rn0_70.feature
        plugins:
          artifacts#v1.5.0:
            download:
              - bin/arm64-macos-bugsnag-cli
            upload:
              - maze_output/**/*

      - label: "RN 0.72 :ios: Integration Tests"
        depends_on: build
        agents:
          queue: macos-12-arm
        env:
          XCODE_VERSION: 14
        commands:
          - chmod +x bin/arm64-macos-bugsnag-cli
          - bundle install
          - bundle exec maze-runner features/react-native-ios/rn0_72.feature
        plugins:
          artifacts#v1.5.0:
            download:
              - bin/arm64-macos-bugsnag-cli
            upload:
              - maze_output/**/*

      - label: "RN 0.69 :android: Integration Tests"
        depends_on: build
        commands:
          - chmod +x bin/arm64-macos-bugsnag-cli
          - bundle install
          - bundle exec maze-runner features/react-native-android/rn0_69.feature
        plugins:
          artifacts#v1.5.0:
            download:
              - bin/arm64-macos-bugsnag-cli
            upload:
              - maze_output/**/*

      - label: "RN 0.70 :android: Integration Tests"
        depends_on: build
        commands:
          - chmod +x bin/arm64-macos-bugsnag-cli
          - bundle install
          - bundle exec maze-runner features/react-native-android/rn0_70.feature
        plugins:
          artifacts#v1.5.0:
            download:
              - bin/arm64-macos-bugsnag-cli
            upload:
              - maze_output/**/*

      - label: "RN 0.72 :android: Integration Tests"
        depends_on: build
        commands:
          - chmod +x bin/arm64-macos-bugsnag-cli
          - bundle install
          - bundle exec maze-runner features/react-native-android/rn0_72.feature
        plugins:
          artifacts#v1.5.0:
            download:
              - bin/arm64-macos-bugsnag-cli
            upload:
              - maze_output/**/*

      - label: RN 0.72 Integration Tests
        depends_on: build
        agents:
          queue: macos-12-arm
        env:
          XCODE_VERSION: 14
        commands:
          - chmod +x bin/arm64-macos-bugsnag-cli
          - bundle install
          - bundle exec maze-runner features/react-native
        plugins:
          artifacts#v1.5.0:
            download:
              - bin/arm64-macos-bugsnag-cli
            upload:
              - maze_output/**/*

      - label: Minidump symbol Integration Tests
        depends_on: build
        agents:
          queue: macos-12-arm
        env:
          XCODE_VERSION: 14
        commands:
          - chmod +x bin/arm64-macos-bugsnag-cli
          - bundle install
          - bundle exec maze-runner features/minidump
        plugins:
          artifacts#v1.5.0:
            download:
              - bin/arm64-macos-bugsnag-cli
            upload:
              - maze_output/**/*
              
