agents:
  queue: macos-12-arm

steps:
  - label: Build CLI Binaries
    key: build
    commands:
      - make build-all
    plugins:
      artifacts#v1.5.0:
        upload: "bin/*"

  # Unit Test
  - label: Unit Test
    commands:
      - make unit-test
    depends_on: build
