agents:
  queue: macos-12-arm

steps:
  - label: Build CLI Binaries
    commands:
      - make build-all
    plugins:
      artifacts#v1.5.0:
        upload: "bin/*"

  # Unit Test
  - label: Unit Test
    commands:
      - make unit-test

- label: E2E Test
  commands:
    - bin/bugsnag-cli-amd64-darwin --help
  plugins:
    artifacts#v1.5.0:
      download: "bin/bugsnag-cli-amd64-darwin"
