agents:
  queue: macos-14

steps:
  - label: Build CLI Binaries
    key: build
    commands:
      - make build-all
    plugins:
      artifacts#v1.5.0:
        upload:
          - bin/**/*

  # Run the unit tests
  - label: Unit Tests
    commands:
      - make unit-tests

  - label: ":lint-roller::go: Lint Go Code"
    commands:
      - make go-lint

  - label: ":lint-roller::npm: Lint NPM Dependencies"
    commands:
      - make npm-lint

  - label: CLI Integration Tests
    depends_on: build
    commands:
      - chmod +x bin/arm64-macos-bugsnag-cli
      - bundle install
      - env
      - bundle exec maze-runner features/cli
    plugins:
      artifacts#v1.5.0:
        download:
          - bin/arm64-macos-bugsnag-cli
        upload:
          - maze_output/**/*

  - label: Android Integration Tests
    depends_on: build
    commands:
      - chmod +x bin/arm64-macos-bugsnag-cli
      - bundle install
      - bundle exec maze-runner features/android
    env:
      JAVA_VERSION: 17
    plugins:
      artifacts#v1.5.0:
        download:
          - bin/arm64-macos-bugsnag-cli
        upload:
          - maze_output/**/*

  - label: Dart Integration Tests
    depends_on: build
    commands:
      - chmod +x bin/arm64-macos-bugsnag-cli
      - bundle install
      - bundle exec maze-runner features/dart
    env:
      FLUTTER_BIN: "/opt/flutter/3.10.0/bin/flutter"
    plugins:
      artifacts#v1.5.0:
        download:
          - bin/arm64-macos-bugsnag-cli
        upload:
          - maze_output/**/*

  - label: React Native Android Integration Tests
    depends_on: build
    commands:
      - chmod +x bin/arm64-macos-bugsnag-cli
      - bundle install
      - bundle exec maze-runner features/react-native-android
    plugins:
      artifacts#v1.5.0:
        download:
          - bin/arm64-macos-bugsnag-cli
        upload:
          - maze_output/**/*

  - label: React Native iOS Integration Tests
    depends_on: build
    env:
      XCODE_VERSION: 15.3.0
    commands:
      - chmod +x bin/arm64-macos-bugsnag-cli
      - bundle install
      - bundle exec maze-runner features/react-native-ios
    plugins:
      artifacts#v1.5.0:
        download:
          - bin/arm64-macos-bugsnag-cli
        upload:
          - maze_output/**/*

  - label: dSYM Integration Tests
    depends_on: build
    env:
      XCODE_VERSION: 15.3.0
    commands:
      - chmod +x bin/arm64-macos-bugsnag-cli
      - bundle install
      - bundle exec maze-runner features/dsym
    plugins:
      artifacts#v1.5.0:
        download:
          - bin/arm64-macos-bugsnag-cli
        upload:
          - maze_output/**/*
