agents:
  queue: macos-12-arm

steps:
  - label: Build CLI Binaries
    key: build
    commands:
      - make build-all
    plugins:
      artifacts#v1.5.0:
        upload:
          - bin/*

  # Unit Test
  - label: Unit Test
    commands:
      - make unit-test

  - label: E2E Test
    depends_on: build
    commands:
      - chmod +x bin/arm64-macos/bugsnag-cli
      - bundle install
      - bundle exec maze-runner
    plugins:
      artifacts#v1.5.0:
        download:
          - bin/arm64-macos/bugsnag-cli
        upload:
          - maze_output/**/*
