agents:
  queue: macos-12-arm

steps:
  - label: Build CLI Binaries
    key: build
    commands:
      - make build-all
    plugins:
      artifacts#v1.5.0:
        upload:
          - bin/**/*

  # Unit Test
  - label: Unit Test
    commands:
      - make unit-test

  - label: Android Integration Tests
    depends_on: build
    commands:
      - chmod +x bin/arm64-macos-bugsnag-cli
      - bundle install
      - env
      - bundle exec maze-runner features/android
    env:
      ANDROID_NDK_ROOT: "/Users/administrator/Library/Android/sdk/ndk/25.1.8937393"
    plugins:
      artifacts#v1.5.0:
        download:
          - bin/arm64-macos-bugsnag-cli
        upload:
          - maze_output/**/*

  - label: Windows E2E Test
    depends_on: build
    commands:
      - chmod +x bin/x86_64-windows-bugsnag-cli.exe
      - bundle install
      - bundle exec maze-runner
    agents:
      queue: windows-general-wsl
    plugins:
      artifacts#v1.5.0:
        download:
          - bin/x86_64-windows-bugsnag-cli.exe
        upload:
          - maze_output/**/*
