agents:
  queue: macos-12-arm

steps:
  - label: Build CLI Binaries
    key: build
    commands:
      - make build-all
    plugins:
      artifacts#v1.5.0:
        upload: "bin/*"

  # Unit Test
  - label: Unit Test
    commands:
      - make unit-test

  - label: E2E Test
    depends_on: build
    commands:
      - bin/bugsnag-cli-amd64-darwin --help
    plugins:
      artifacts#v1.5.0:
        download: "bin/bugsnag-cli-amd64-darwin"
