agents:
  queue: macos-14

steps:
  - label: Build CLI Binaries
    key: build
    commands:
      - make build-all
    plugins:
      artifacts#v1.5.0:
        upload:
          - bin/**/*

  - group: ":lint-roller: Linting"
    steps:
      - label: ":lint-roller::go: Lint Go Code"
        commands:
          - make go-lint
      - label: ":lint-roller::npm: Lint NPM Dependencies"
        commands:
          - make npm-lint

  # Run the unit tests
  - label: Unit Tests
    commands:
      - make unit-tests

  - label: ":terminal: CLI Integration Tests"
    depends_on: build
    env:
      NODE_VERSION: 18
    commands:
      - bundle install
      - chmod +x bin/arm64-macos-bugsnag-cli
      - bundle exec maze-runner features/cli
    plugins:
      artifacts#v1.5.0:
        download:
          - bin/arm64-macos-bugsnag-cli
        upload:
          - maze_output/**/*

  - label: ":android: Integration Tests"
    depends_on: build
    commands:
      - bundle install
      - chmod +x bin/arm64-macos-bugsnag-cli
      - bundle exec maze-runner features/android
    env:
      JAVA_VERSION: 17
    plugins:
      artifacts#v1.5.0:
        download:
          - bin/arm64-macos-bugsnag-cli
        upload:
          - maze_output/**/*

  - label: ":dartlang: Integration Tests"
    depends_on: build
    commands:
      - bundle install
      - chmod +x bin/arm64-macos-bugsnag-cli
      - bundle exec maze-runner features/dart
    env:
      FLUTTER_BIN: "/opt/flutter/3.19.0/bin/flutter"
    plugins:
      artifacts#v1.5.0:
        download:
          - bin/arm64-macos-bugsnag-cli
        upload:
          - maze_output/**/*

  - label: dSYM Integration Tests
    depends_on: build
    env:
      XCODE_VERSION: 15
    commands:
      - bundle install
      - chmod +x bin/arm64-macos-bugsnag-cli
      - bundle exec maze-runner features/dsym
    plugins:
      artifacts#v1.5.0:
        download:
          - bin/arm64-macos-bugsnag-cli
        upload:
          - maze_output/**/*

  - label: ":javascript: Integration Tests"
    depends_on: build
    commands:
      - chmod +x bin/arm64-macos-bugsnag-cli
      - bundle install
      - bundle exec maze-runner features/js
    plugins:
      artifacts#v1.5.0:
        download:
          - bin/arm64-macos-bugsnag-cli
        upload:
          - maze_output/**/*

  - label: Unity Android Integration Tests
    depends_on: build
    env:
      UNITY_VERSION: 2023.2.19f1
    commands:
      - chmod +x bin/arm64-macos-bugsnag-cli
      - bundle install
      - bundle exec maze-runner features/unity-android
    plugins:
      artifacts#v1.5.0:
        download:
          - bin/arm64-macos-bugsnag-cli
        upload:
          - maze_output/**/*

  - group: ":react: React Native"
    steps:
      - label: RN 0.69 iOS Integration Tests
        depends_on: build
        agents:
          queue: macos-12-arm
        env:
          XCODE_VERSION: 13.4.1
        commands:
          - chmod +x bin/arm64-macos-bugsnag-cli
          - bundle install
          - bundle exec maze-runner features/react-native-ios/rn0_69.feature
        plugins:
          artifacts#v1.5.0:
            download:
              - bin/arm64-macos-bugsnag-cli
            upload:
              - maze_output/**/*

      - label: RN 0.70 iOS Integration Tests
        depends_on: build
        agents:
          queue: macos-12-arm
        env:
          XCODE_VERSION: 13.4.1
        commands:
          - chmod +x bin/arm64-macos-bugsnag-cli
          - bundle install
          - bundle exec maze-runner features/react-native-ios/rn0_70.feature
        plugins:
          artifacts#v1.5.0:
            download:
              - bin/arm64-macos-bugsnag-cli
            upload:
              - maze_output/**/*

      - label: RN 0.72 iOS Integration Tests
        depends_on: build
        #        agents:
        #          queue: macos-12-arm
        #        env:
        #          XCODE_VERSION: 13.4.1
        commands:
          - chmod +x bin/arm64-macos-bugsnag-cli
          - bundle install
          - bundle exec maze-runner features/react-native-ios/rn0_72.feature
        plugins:
          artifacts#v1.5.0:
            download:
              - bin/arm64-macos-bugsnag-cli
            upload:
              - maze_output/**/*

#      - label: React Native Android Integration Tests
#        depends_on: build
#        commands:
#          - chmod +x bin/arm64-macos-bugsnag-cli
#          - bundle install
#          - bundle exec maze-runner features/react-native-android
#        plugins:
#          artifacts#v1.5.0:
#            download:
#              - bin/arm64-macos-bugsnag-cli
#            upload:
#              - maze_output/**/*
#
#      - label: React Native Integration Tests
#        depends_on: build
#        agents:
#          queue: macos-12-arm
#        commands:
#          - chmod +x bin/arm64-macos-bugsnag-cli
#          - bundle install
#          - bundle exec maze-runner features/react-native
#        plugins:
#          artifacts#v1.5.0:
#            download:
#              - bin/arm64-macos-bugsnag-cli
#            upload:
#              - maze_output/**/*
