agents:
  queue: macos-12-arm

steps:
  - label: Build CLI Binaries
    key: build
    commands:
      - make build-all
    plugins:
      artifacts#v1.5.0:
        upload:
          - bin/**/*

  # Unit Test
  - label: Unit Test
    commands:
      - make unit-test

  - label: CLI Integration Tests
    depends_on: build
    commands:
      - chmod +x bin/arm64-macos-bugsnag-cli
      - bundle install
      - env
      - bundle exec maze-runner features/cli
    plugins:
      artifacts#v1.5.0:
        download:
          - bin/arm64-macos-bugsnag-cli
        upload:
          - maze_output/**/*

  - label: Android Integration Tests
    depends_on: build
    commands:
      - chmod +x bin/arm64-macos-bugsnag-cli
      - bundle install
      - env
      - bundle exec maze-runner features/android
    env:
      JAVA_VERSION: 17
    plugins:
      artifacts#v1.5.0:
        download:
          - bin/arm64-macos-bugsnag-cli
        upload:
          - maze_output/**/*

  - label: Dart Integration Tests
    depends_on: build
    commands:
      - chmod +x bin/arm64-macos-bugsnag-cli
      - bundle install
      - bundle exec maze-runner features/dart
    env:
      FLUTTER_BIN: "/opt/flutter/3.10.0/bin/flutter"
      JAVA_VERSION: 17
    plugins:
      artifacts#v1.5.0:
        download:
          - bin/arm64-macos-bugsnag-cli
        upload:
          - maze_output/**/*

  - label: React Native Android Integration Tests
    depends_on: build
    commands:
      - chmod +x bin/arm64-macos-bugsnag-cli
      - bundle install
      - bundle exec maze-runner features/react-native-android
    plugins:
      artifacts#v1.5.0:
        download:
          - bin/arm64-macos-bugsnag-cli
        upload:
          - maze_output/**/*
