agents:
  queue: ms-arm-12-8

steps:
  - label: Build CLI Binary
    commands:
      - make build-all
    plugins:
      artifacts#v1.5.0:
        upload: "build/*"

  - label: Run CLI Tests
    commands:
      - bundle install
      - bundle exec maze-runner
    plugins:
      artifacts#v1.5.0:
        download: "build/*"